name: finance
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.

version: 1.0.0+1

environment:
  sdk: ^3.6.0

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  go_router: ^16.1.0
  flutter_svg: ^2.2.0
  flutter_otp_text_field: ^1.5.1+1
  u_credit_card: ^1.4.0
  carousel_slider: ^5.1.2
  dots_indicator: ^4.0.1
  mrx_charts: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices.
  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/Icons/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section.
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Bold.ttf
        - asset: assets/fonts/Urbanist-MediumItalic.ttf
          style: italic
        - asset: assets/fonts/Urbanist-Regular.ttf